name: Our Artifacts 2
on: push
jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: hello.txt
  down:
    runs-on: ubuntu-latest
    needs: up
    steps:
      - run: cat artifacts.txt
        continue-on-error: true
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
      - run: cat artifacts.txt
