name: Our Deployment
on: push

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable.yml
    with:
      env: dev

  deploy-qa:
    needs: [deploy-dev]
    uses: ./.github/workflows/reusable.yml
    with:
      env: qa

  deploy-prod:
    needs: [deploy-qa]
    uses: ./.github/workflows/reusable.yml
    with:
      env: prod
      notify: true
