name: Our Reusable
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      notify:
        type: boolean
        default: false

jobs:
  deploy:
    environment: inputs.env
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: install
        run: npm ci
      - name: test
        run: npm test
      - name: build
        run: npm run build
      # - name: deploy
      #   run: npm run deploy
      - name: notify
        if: inputs.notify
        run: echo 'Deployment completed in ${{ inputs.env }}! 🎉'
